services:
  ui:
    build: ui

  pwa:
    build: pwa

  git:
    build:
      context: .
      dockerfile: git.Dockerfile

  front:
    build:
      context: front
      additional_contexts:
        deciphraze-ui: service:ui
        deciphraze-pwa: service:pwa
        deciphraze-git: service:git
    develop:
      watch:
        - action: sync
          path: ./front/src
          target: /deciphraze/front/src
        - action: sync
          path: ./front/index.html
          target: /deciphraze/front
        - action: rebuild
          path: ./front/package.json
        - action: rebuild
          path: ./ui
        - action: rebuild
          path: ./pwa
    ports:
      - "1111:1111"

  stryker:
    build:
      context: front
      additional_contexts:
        deciphraze-ui: service:ui
        deciphraze-pwa: service:pwa
        deciphraze-git: service:git
      dockerfile: stryker.Dockerfile
    ports:
      - "1112:1112"