services:
  frontend-deps:
    build:
      context: .
      target: deps

  frontend:
    build:
      context: .
      additional_contexts:
        deciphraze-frontend-deps: service:frontend-deps
    develop:
      watch:
        - action: sync
          path: ./src
          target: /deciphraze/src
        - action: rebuild
          path: ./package.json
    ports:
      - "1111:1111"