services:
  ds:
    build: ds

  git:
    build:
      context: .
      dockerfile: git.Dockerfile

  front:
    build:
      context: front
      additional_contexts:
        deciphraze-ds: service:ds
        deciphraze-git: service:git
    develop:
      watch:
        - action: sync
          path: ./front/src
          target: /deciphraze/front/src
        - action: rebuild
          path: ./front/package.json
    ports:
      - "1111:1111"

  stryker:
    build:
      context: front
      additional_contexts:
        deciphraze-ds: service:ds
        deciphraze-git: service:git
      dockerfile: stryker.Dockerfile
    ports:
      - "1112:1112"